### PR TITLE
Enumerable Methods

### PR DESCRIPTION
**Pull request by Qoosim**
This project rebuilt some Ruby Enumerable methods

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello @Qoosim   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. The pull request should have a [descriptive name and a short description](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).

2. Please correct the following: 

- for the methods: **my_each, my_each_with_index, my_select, my_none, my_count, my_map and my_inject** you need to make them work in case no block is given, check this link for [reference](https://ruby-doc.org/core-2.6.2/Enumerable.html).

3. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by shshamim63** [comment]
## Status :recycle:  [!! Changes Required !!]  :recycle: 
___
Hi @Qoosim :wave: .
Well done :clap: . You are almost there. except some methods your project looks nice. But those issues are really necessary to cover. And i am sure that you will cover them all :sunglasses: .
___
##### Please follow the instructions below :point_down:  to complete this project.
___
###  :pick: [Mandatory Changes] :pick: 
___
1. **[my_select](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select)** -> 
select works as, if the item from array met up with the given condition returns a new array. So condition could be anyone. But on your one you have made a static block call that is only for even numbers. What if I want to select those element which are grater than 1. `[1,2,3].my_select {|num| num > 1 }`. So instead of it
https://github.com/Qoosim/enumerables_methods/blob/77c927b57d0988b6a66cc3b2e4bdb3cdafa88c5c/enumerables.rb#L35
`array_result << self[k] if yield(self[k])` this should take place.
2. **[my_none](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F)**- > This actually  opposite of `my_any`. Which checks for if none of the item is matching the provided matching.
for an example [1, 2, 3].my_none? should return false and [1, 2, nil].my_none? should return true.
:fire: Hint: same as my_any? except true will be boolean will be altered.
3. **[my_count](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count)** ->
..1. Counts the number of items in enum that are equal to item if an argument is given. `[2, 2, 1].count(2)` should return 2.
..2. If no block or argument is given return the number of elements that are not nil | false | undefined.
`[1, 2, nil].count` should return 2.
4. **[my_inject](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject)**-> my_inject takes two argument, initial and symbol. The operations are as below.
..1. `[1, 2, 3].my_inject(2) { |prod, n | prod + n}` and `[1, 2, 3].my_inject(2, :+)` both should return 8.
___
### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

Well done doing the changes, however not all the required changes have been implemented:

- Please give the pull request should have a [descriptive name and a short description](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Review by Redvanisation — APPROVED** [review]
# Project approved ✔️ 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
